# Generated by Django 3.2.7 on 2021-09-07 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('board_game', 'Board games'), ('sport_game', 'Sport games'), ('ps4', 'Sony Playstation'), ('watching', 'Watching film/anime'), ('other', 'Others')], default='board_games', max_length=50),
        ),
    ]
