# Generated by Django 3.2.7 on 2021-09-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210907_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='event', max_length=150),
            preserve_default=False,
        ),
    ]
