# Generated by Django 3.2.7 on 2021-09-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210907_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_time',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
