# Generated by Django 3.2.7 on 2021-09-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210911_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='body',
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(default='Details', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='short_desc',
            field=models.TextField(default='Details', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique_for_date='date_time'),
        ),
    ]
