# Generated by Django 3.2.7 on 2021-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210912_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='luxe',
            field=models.BooleanField(default=False),
        ),
    ]
