# Generated by Django 3.2.7 on 2021-10-07 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20211006_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='follows',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Board game', 'Board games'), ('Sport games', 'Sport games'), ('Sony Playstation', 'Sony Playstation'), ('Watching film/anime', 'Watching film/anime'), ('Others', 'Others')], default='Board games', max_length=50),
        ),
    ]
