# Generated by Django 3.2.7 on 2021-10-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211007_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='follows',
        ),
    ]
