# Generated by Django 3.2.7 on 2021-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_mini',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='', verbose_name='Avatar_mini'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
    ]
