# Generated by Django 3.2.7 on 2021-10-09 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211009_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 9), null=True, verbose_name='Image date'),
        ),
    ]
