# Generated by Django 3.2.7 on 2021-10-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_profile_avatar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_date',
            field=models.DateField(blank=True, null=True, verbose_name='Image date'),
        ),
    ]
